// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9vxqWEfIKbon_8bUDkvY7-5a5Uzaw0eM',
    appId: '1:510046958869:web:7a74d3224865061c97e51c',
    messagingSenderId: '510046958869',
    projectId: 'school-fee-feefc',
    authDomain: 'school-fee-feefc.firebaseapp.com',
    storageBucket: 'school-fee-feefc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKPMmsiNy3IlcovcetL1FGginjDIQhmAA',
    appId: '1:510046958869:android:e7560435dd8f759e97e51c',
    messagingSenderId: '510046958869',
    projectId: 'school-fee-feefc',
    storageBucket: 'school-fee-feefc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDO7I3v9Dc6hnl5bmndfpqTbES8Zjv23o',
    appId: '1:510046958869:ios:b6b22b83d1f4ad9497e51c',
    messagingSenderId: '510046958869',
    projectId: 'school-fee-feefc',
    storageBucket: 'school-fee-feefc.firebasestorage.app',
    iosBundleId: 'com.example.scdAssignment1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDO7I3v9Dc6hnl5bmndfpqTbES8Zjv23o',
    appId: '1:510046958869:ios:b6b22b83d1f4ad9497e51c',
    messagingSenderId: '510046958869',
    projectId: 'school-fee-feefc',
    storageBucket: 'school-fee-feefc.firebasestorage.app',
    iosBundleId: 'com.example.scdAssignment1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9vxqWEfIKbon_8bUDkvY7-5a5Uzaw0eM',
    appId: '1:510046958869:web:9f2b72ba388aed4597e51c',
    messagingSenderId: '510046958869',
    projectId: 'school-fee-feefc',
    authDomain: 'school-fee-feefc.firebaseapp.com',
    storageBucket: 'school-fee-feefc.firebasestorage.app',
  );

}